import React, { Suspense, useRef, useState, useEffect } from 'react';
import { Canvas } from '@react-three/fiber';
import { Center, OrbitControls } from '@react-three/drei';
import VolumetricPlayer from '../3D/VolumetricPlayer2';

export default function Viewport({ resultPath }) {
  const videoRef = useRef(null);
  const controlsRef = useRef(null);

  const [isPlaying, setIsPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(1);
  const [colorMode, setColorMode] = useState('rgb');

  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;

    const updateTime = () => setCurrentTime(video.currentTime);
    const updateDuration = () => setDuration(video.duration);

    // Ensure state matches actual playback if it pauses to buffer
    const handlePlay = () => setIsPlaying(true);
    const handlePause = () => setIsPlaying(false);

    video.addEventListener('timeupdate', updateTime);
    video.addEventListener('loadedmetadata', updateDuration);
    video.addEventListener('play', handlePlay);
    video.addEventListener('pause', handlePause);

    return () => {
      video.removeEventListener('timeupdate', updateTime);
      video.removeEventListener('loadedmetadata', updateDuration);
      video.removeEventListener('play', handlePlay);
      video.removeEventListener('pause', handlePause);
    };
  }, [resultPath]);

  const togglePlay = () => {
    if (isPlaying) {
      videoRef.current.pause();
    } else {
      videoRef.current.play();
    }
  };

  const handleSeek = (e) => {
    const time = parseFloat(e.target.value);
    videoRef.current.currentTime = time;
    setCurrentTime(time);
  };

  const resetCamera = () => {
    if (controlsRef.current) {
      // 1. Access the camera through the controls
      const camera = controlsRef.current.object;

      // 2. Set the physical position of the camera
      camera.position.set(0, 0, -8);

      // 3. Set the point the camera is looking at (the pivot)
      controlsRef.current.target.set(0, 0, 0);

      // 4. IMPORTANT: Tell the controls to sync up with the new camera math
      controlsRef.current.update();
    }
  };

  // Point to the new combined video generated by the backend
  const videoSrc = resultPath ? `file://${resultPath.replace(/\\/g, '/')}/combined.mp4` : null;

  return (
    <section className="flex-1 relative bg-black titlebar-drag-region flex flex-col">
      <div className="flex-1 relative overflow-hidden">
        {resultPath ? (
          <Suspense fallback={<LoadingState />}>
            <video ref={videoRef} src={videoSrc} loop muted playsInline className="hidden" crossOrigin="anonymous" />

            <div className="w-full h-full no-drag cursor-crosshair">
              <Canvas camera={{ position: [0, 0, -8], fov: 50 }}>
                <ambientLight intensity={1.5} />
                <directionalLight position={[0, 0, 5]} intensity={1} />
                <OrbitControls ref={controlsRef} makeDefault enablePan={true} />

                <Center>
                  <VolumetricPlayer
                    videoRef={videoRef}
                    colorMode={colorMode}
                  />
                </Center>
              </Canvas>
            </div>
          </Suspense>
        ) : (
          <EmptyState />
        )}
      </div>

      {resultPath && (
        <div className="h-20 bg-zinc-950 border-t border-zinc-800 flex items-center px-6 gap-6 no-drag">
          <button
            onClick={togglePlay}
            className="w-12 h-12 flex items-center justify-center bg-zinc-900 border border-zinc-700 hover:border-lime-400 text-lime-400 transition-colors"
          >
            {isPlaying ? "||" : "▶"}
          </button>

          <div className="flex-1 flex items-center gap-4">
            <span className="text-[10px] text-zinc-500 font-mono w-10 text-right">{currentTime.toFixed(1)}s</span>
            <input
              type="range"
              min={0}
              max={duration || 1}
              step={0.01}
              value={currentTime}
              onChange={handleSeek}
              className="flex-1 accent-lime-400 h-1 bg-zinc-800 appearance-none cursor-ew-resize"
            />
            <span className="text-[10px] text-zinc-500 font-mono w-10">{duration.toFixed(1)}s</span>
          </div>

          <div className="flex gap-2">
            <button
              onClick={() => setColorMode(colorMode === 'rgb' ? 'depth' : 'rgb')}
              className="px-4 py-2 text-[10px] font-bold tracking-widest border border-zinc-700 hover:border-lime-400 text-zinc-400 hover:text-lime-400"
            >
              MODE: {colorMode.toUpperCase()}
            </button>
            <button
              onClick={resetCamera}
              className="px-4 py-2 text-[10px] font-bold tracking-widest border border-zinc-700 hover:border-lime-400 text-zinc-400 hover:text-lime-400"
            >
              RESET VIEW
            </button>
          </div>
        </div>
      )}
    </section>
  );
}

const LoadingState = () => (
  <div className="absolute inset-0 flex items-center justify-center text-lime-400 font-mono text-xs animate-pulse">
    INITIALIZING_VOLUMETRIC_PLAYER...
  </div>
);

const EmptyState = () => (
  <div className="absolute inset-0 flex flex-col items-center justify-center opacity-20 select-none">
    <div className="text-[120px] font-black text-zinc-800 leading-none">NULL</div>
    <div className="font-mono text-xs tracking-[1em] text-zinc-600 mt-4">AWAITING DATA STREAM</div>
  </div>
);